Track non-deterministic transitions for initial states
rustype/typestate-rs pull request #33
Opened 2022-05-16 20:02 UTC by tryone144

Properly track non-deterministic transitions when used as initial states. Otherwise, compilation fails with `error: Unused transitions are not allowed.` if such a transition is only used on initial states.

## Example Code

<details>
<summary>Simplified TrafficLight example...</summary>

```rust
use traffic_light::*;
use typestate::typestate;

fn main() {
    let light = TrafficLight::<Red>::turn_on();
    if let Either::Red(red_light) = light {
        let green_light = red_light.to_green();
        let red_light = green_light.to_red();
        red_light.turn_off();
    }
}

#[typestate]
mod traffic_light {
    #[derive(Debug)]
    #[automaton]
    pub struct TrafficLight {}
    #[state]
    pub struct Green;
    #[state]
    pub struct Red;

    pub trait Green {
        fn to_red(self) -> Red;
    }
    pub trait Red {
        fn to_green(self) -> Green;
        fn turn_on() -> Either;
        fn turn_off(self);
    }

    pub enum Either {
        Green,
        Red,
    }
}

impl GreenState for TrafficLight<Green> {
    fn to_red(self) -> TrafficLight<Red> {
        println!("Green -> Red");
        TrafficLight::<Red> {
            state: Red,
        }
    }
}

impl RedState for TrafficLight<Red> {
    fn to_green(self) -> TrafficLight<Green> {
        println!("Red -> Green");
        TrafficLight::<Green> {
            state: Green,
        }
    }

    fn turn_on() -> Either {
        println!("Turning on...");
        Either::Red(TrafficLight::<Red> {
            state: Red,
        })
    }

    fn turn_off(self) {
        println!("Turning off...");
        // ... consume
    }
}
```

</details>

---

Let me know if you need a proper test for these cases.

2022-05-20 15:20 UTC, jmg-duarte requested changes
Along with the current change, please add a test for your use-case

2022-05-20 23:38 UTC, tryone144 commented
I've added a (simplified) test-case. Please have a look if this is sufficient.

2022-05-21 19:28 UTC, jmg-duarte requested changes
Please address the name comment, otherwise it LGTM

2022-05-21 19:28 UTC, jmg-duarte commented on tests/pass/non-deterministic_initial_state.rs
> +        fn start() -> Failable;
The correct state name would be `Fallible`

2022-05-22 11:20 UTC, merged